[".config/opencode"]
    type = "git-repo"
    url = "git@github.com:xnoto/opencode-config.git"
    pull.args = ["--ff-only"]

["git/anthropics/skills"]
    type = "git-repo"
    url = "https://github.com/anthropics/skills.git"
    clone.args = ["--depth", "1"]
    pull.args = ["--ff-only"]

[".config/alacritty/alacritty-theme-linux-vconsole"]
    type = "git-repo"
    url = "git@github.com:xnoto/alacritty-theme-linux-vconsole.git"

[".config/alacritty/themes"]
    type = "git-repo"
    url = "https://github.com/alacritty/alacritty-theme"
