[cursor]
style = { shape = "Block", blinking = "Always" }

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 16.0

[font.normal]
family = "Px437 IBM VGA 8x16"
style = "Regular"

[font.bold]
family = "Px437 IBM VGA 8x16"
style = "Regular"

[general]
import = [
    "~/.config/alacritty/alacritty-theme-linux-vconsole/linux-vconsole.toml"
]

[env]
TERM = "xterm-256color"
